name: 'new_first_project'   # 👈 This must match your dbt Cloud project name
version: '1.0'
config-version: 2

profile: 'default'          # 👈 Use your connection profile (e.g., for Snowflake)

model-paths: ["models"]
seed-paths: ["seeds"]

