name: 'new_first_project'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]

seeds:
  new_first_project:
    employee_data:
      column_types:
        employee_id: integer
        employee_name: string
        department: string
