version: 2 
sources:
  - name: netflix
    schema: raw
    tables:
     - name: movies
       identifier: raw_movies
     - name: ratings
       identifier: raw_ratings
     - name: tags
       identifier: raw_tags
     - name: genome_tags
       identifier: raw_genome_tags
     - name: genome_scores
       identifier: raw_genome_scores
     - name: links
       identifier: raw_links