version: 2

sources:
  - name: public
    database: TEST_DB      # ← Your Snowflake DB name
    schema: PUBLIC         # ← Your Snowflake schema
    tables:
      - name: customer_raw

models:
  - name: stg_customer
    description: "Staging model for customer data"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique


