version: 2

sources:
  - name: netflix          # <-- must match your source() call
    database: TEST_DB      # <-- your Snowflake database
    schema: PUBLIC         # <-- your Snowflake schema
    tables:
      - name: movies     # <-- your actual raw table name
