version: 2

sources:
  - name: raw
    database: TEST_DB       # replace with your Snowflake database
    schema: PUBLIC          # replace with your schema
    tables:
      - name: movies
      - name: ratings
      - name: tags
      - name: genome_tags
      - name: genome_scores
      - name: links

models:
  - name: stg_movies
    description: "Staging model for movies data"
    columns:
      - name: movie_id
        description: "Unique movie identifier"
        tests:
          - not_null
          - unique
      - name: title
        description: "Movie title"

  - name: stg_ratings
    description: "Staging model for ratings data"
    columns:
      - name: user_id
        tests:
          - not_null
      - name: movie_id
        tests:
          - not_null
      - name: rating
        description: "User rating for the movie"

  - name: stg_tags
    description: "Staging model for tags"
    columns:
      - name: user_id
        tests:
          - not_null
      - name: movie_id
        tests:
          - not_null
      - name: tag
        description: "User-defined tag"

  - name: stg_genome_tags
    description: "Staging model for genome tags"
    columns:
      - name: tag_id
        tests:
          - not_null
          - unique
      - name: tag
        description: "Tag description"

  - name: stg_genome_scores
    description: "Staging model for genome scores"
    columns:
      - name: movie_id
        tests:
          - not_null
      - name: tag_id
        tests:
          - not_null
      - name: relevance
        description: "Relevance score of the tag for the movie"

  - name: stg_links
    description: "Staging model for external links"
    columns:
      - name: movie_id
        tests:
          - not_null
          - unique
      - name: imdb_id
        description: "IMDB identifier"
      - name: tmdb_id
        description: "TMDB identifier"
